name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # tous les jours à minuit
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: uns111code
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit files
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate contribution snake 🐍"
          add: "dist/*.svg"
